version: "3.9"

services:
  clinet:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - spotify-app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      NODE_ENV: production
    networks:
      - spotify-app-network

networks:
  spotify-app-network:
    driver: bridge
