version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react_server
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - app_network

  backend:
    build:
      context: ./server/
      dockerfile: Dockerfile
    container_name: node_backend
    ports:
      - "9000:9000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

